### ISSUE TITLE
Spelling error and missing link

### ISSUE THREAD

**Issue by LindseyBrooks** [ibm-cloud-docs/planning-analytics#2]
On this page: https://cloud.ibm.com/docs/planning-analytics?topic=planning-analytics-Administer
... the link: 'Administration taks unique to Planning Analytics as a Service' has a spelling error. It says 'taks' instead of 'tasks'. Also the link goes through to the PA on Cloud documentation home page rather than to a page specific to the topic it is describing.

Background on me... I am a CSM for IBM working with Planning Analytics customers. So I'm keen to track the resolution of this issue.

**Comment by briantoohey** [comment]
Spelling issue corrected, all content moving to IBM Docs, full topic reorganization

**Comment by LindseyBrooks** [comment]
Thank you. Wow so long ago, I forgot I ever raised this ticket ;) But thank you for following through :)
